name: Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        default: 'dev'
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Validate user input
      - name: Validate input
        run: |
          STAGE="${{ github.event.inputs.stage }}"
          if [[ "$STAGE" != "dev" && "$STAGE" != "qa" && "$STAGE" != "prod" ]]; then
            echo "❌ Invalid stage: $STAGE. Please choose from dev, qa, or prod."
            exit 1
          fi
          echo "✅ Valid stage: $STAGE"

      # Step 2: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Configure AWS credentials from GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'

      # Step 5: Run Terraform Init and Apply
      - name: Apply Terraform configuration
        env:
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate

          terraform apply -auto-approve \
            -var-file="${{ github.event.inputs.stage }}.json" \
            -var="stage=${{ github.event.inputs.stage }}" \
            -var="github_token=${{ secrets.GH_TOKEN }}"

      # Step 6: Health check after EC2 deployment
      - name: Validate app health
        run: |
          STAGE="${{ github.event.inputs.stage }}"

          echo "--- Fetching EC2 Public IP for stage: $STAGE"
          EC2_PUBLIC_IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=MyInstance-$STAGE" \
            --query 'Reservations[].Instances[].PublicIpAddress' \
            --output text)

          if [[ -z "$EC2_PUBLIC_IP" ]]; then
            echo "❌ Could not retrieve EC2 Public IP."
            exit 1
          fi

          echo "✅ EC2 Public IP: $EC2_PUBLIC_IP"
          echo "--- Waiting 3 minutes for the app to start..."
          sleep 180

          echo "--- Performing health check at http://$EC2_PUBLIC_IP:80"
          if curl -f http://$EC2_PUBLIC_IP:80; then
            echo "✅ App is healthy and responding!"
          else
            echo "❌ App is not responding on port 80."
            exit 1
          fi
