name: Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        default: 'dev'
        options:
          - dev
          - qa
          - prod 
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate input
        run: |
          if [[ "${{ github.event.inputs.stage }}" != "dev" && "${{ github.event.inputs.stage }}" != "qa" && "${{ github.event.inputs.stage }}" != "prod" ]]; then
            echo "Invalid input: ${{ github.event.inputs.stage }}. Please use one of the following: dev, qa, prod."
            exit 1
          fi
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-output: json

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.3'

      - name: Apply Terraform configuration
        # Use the 'env' block to pass the GitHub token as a Terraform variable
        env:
          # Terraform automatically picks up environment variables prefixed with TF_VAR_
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
        run: |
          VAR_FILE="${{ github.event.inputs.stage }}.tfvars"
          # Check if the var file exists (optional, but good practice)
          if [ ! -f "./terraform/$VAR_FILE" ]; then
            echo "Error: Variable file $VAR_FILE not found in ./terraform/"
            exit 1
          fi
          terraform apply -var-file="$VAR_FILE" --auto-approve \
            -var "stage=${{ github.event.inputs.stage }}"
        working-directory: ./terraform # Ensure this path is correct for your Terraform files


      - name: Validate app health
        run: |
          EC2_PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=MyInstance" --query 'Reservations[].Instances[].PublicIpAddress' --output text)
          sleep 120
          curl -f http://$EC2_PUBLIC_IP:80
          curl -f http://$EC2_PUBLIC_IP:8080
