name: EC2 Deploy via terraform

on:
  push:
    branches:
      - main

    tags:
      - deploy-dev
      - deploy-prod

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION}}

      - name: Terraform init
        run: terraform init
        
      - name: Terraform apply
        run: terraform apply -auto-approve -var-file="dev.tfvars" 
        
      - name: Get EC2 Public IP
        id: ec2_ip
        run: |
          ip=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=techeazy-instance" \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            -- output text)
            
          echo "EC2_PUBLIC_IP=$ip" >> $GITHUB_ENV  


      - name: Wait for EC2 SSH
        run: |
          sleep 60
          echo "Waiting for ec2 to be ready.."


      - name: Run deployement Script via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_PUBLIC_IP}}   
          username: ec2-user
          key: ${{ secrets.INSTANCE_KEY}} 
          script: |
            chmod +x ~/scripts/deploy.sh
            ~/scripts/deploy.sh techeazy-bucket

      - name: Verfiy App Health
        run: |
          curl --fail http://${{ env.EC2_PUBLIC_IP}} || exit 1      