name: Destroy EC2 via Terraform

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Environment to destroy (dev, qa, prod)'
        required: true
        default: 'dev'
        options:
          - dev
          - qa
          - prod

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Stage
        id: set_stage
        run: |
          STAGE="${{ github.event.inputs.stage }}"
          echo "stage=$STAGE" >> "$GITHUB_OUTPUT"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'

      - name: Terraform Init and Destroy
        env:
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
        run: |
          cd terraform
          terraform init
          terraform validate
          terraform destroy -auto-approve \
            -var-file="${{ steps.set_stage.outputs.stage }}.json" \
            -var="stage=${{ steps.set_stage.outputs.stage }}" \
            -var="github_token=${{ secrets.GH_TOKEN }}"

