name: Destroy Infrastructure via Terraform

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Environment to destroy (dev, qa, prod)'
        required: true
        default: dev

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'

      - name: Terraform Init and Destroy
        env:
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
        run: |
          cd terraform
          terraform init
          terraform validate
          terraform destroy -auto-approve \
            -var-file="${{ github.event.inputs.stage }}.json" \
            -var="stage=${{ github.event.inputs.stage }}" \
            -var="github_token=${{ secrets.GH_TOKEN }}"
