name: Destroy EC2 Infrastructure

on:
  workflow_dispatch # allows you to trigger manually from github UI


jobs:
    destroy:
        runs-on: ubuntu-latest
        env:
            AWS_REGION: us-east-1  

        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            
            
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
                
          - name: Install Terraform
            uses: hashicorp/setup-terraform@v2
            with:
                terraform_version: 1.5.7     

          - name: Terraform init 
            working-directory: ./terraform   
            run: terraform init
            
          - name: Terraform destroy 
            working-directory: ./terraform
            run: terraform destroy -auto-approve -var-file="dev.tfvars"


